name: nova

services:
  auth_db:
    image: postgres:18.4-alpine3.24
    container_name: auth_db
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-nova_auth}
    ports:
      - "5432:5432"
    networks:
      - nova_network

networks:
  nova_network:
    driver: bridge