name: nova

services:
  nova_db:
    image: postgres:14.24-alpine3.23
    container_name: nova_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nova
    ports:
      - "5432:5432"
    networks:
      - nova_network
    volumes:
      - nova_db_data:/var/lib/postgresql/data

networks:
  nova_network:
    driver: bridge
volumes:
  nova_db_data: